# Generated by Django 3.1.14 on 2022-01-03 04:22

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_purchasedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_reviews',
            field=models.PositiveIntegerField(default=products.models.Product.random_review),
        ),
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.FloatField(default=products.models.Product.random_star),
        ),
    ]
